name: HarmonyOS CI/CD Pipeline

on:
  push:
    branches:
      - master  # 触发分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 JDK 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. 缓存 HarmonyOS 命令行工具
    - name: Cache HarmonyOS CLI tools
      id: cache-tools
      uses: actions/cache@v3
      with:
        path: harmonyos-tools  # 缓存路径
        key: harmonyos-tools-${{ runner.os }}-${{ hashFiles('harmonyos-tools/commandline-tools-linux.zip') }}  # 缓存键
        restore-keys: |
          harmonyos-tools-${{ runner.os }}-

    # 4. 下载 HarmonyOS 命令行工具（如果缓存未命中）
    - name: Download HarmonyOS CLI tools (if not cached)
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: |
        mkdir -p harmonyos-tools
        wget -O harmonyos-tools/commandline-tools-linux.zip https://harmonytools.sanchuanhehe.com/commandline-tools-linux-x64-5.0.7.100.zip
        unzip harmonyos-tools/commandline-tools-linux.zip -d harmonyos-tools/

    # 5. 配置环境变量
    - name: Set up environment variables
      run: |
        echo "COMMANDLINE_TOOL_DIR=$(pwd)/harmonyos-tools" >> $GITHUB_ENV
        echo "PATH=$(pwd)/harmonyos-tools/command-line-tools/bin:$PATH" >> $GITHUB_ENV
        echo "HDC_HOME=$(pwd)/harmonyos-tools/command-line-tools/sdk/default/openharmony/toolchains" >> $GITHUB_ENV
        echo "PATH=$HDC_HOME:$PATH" >> $GITHUB_ENV

    # 6. 安装项目依赖
    - name: Install project dependencies
      run: |
        cd ${{ github.workspace }}
        ohpm install --all  # 安装主工程依赖
        ohpm install --all --directory entry  # 安装 entry 模块的三方依赖

    # 7. 构建 HAP 文件
    - name: Build HAP
      run: |
        cd ${{ github.workspace }}
        hvigorw clean --no-daemon
        hvigorw assembleHap --mode module -p product=default -p buildMode=debug --no-daemon

    # 8. 签名 HAP 文件
    - name: Sign HAP
      run: |
        cd ${{ github.workspace }}
        java -jar $COMMANDLINE_TOOL_DIR/command-line-tools/sdk/default/openharmony/toolchains/lib/hap-sign-tool.jar \
        sign-app \
        -keyAlias "ide_demo_app" \
        -signAlg "SHA256withECDSA" \
        -mode "localSign" \
        -appCertFile "signing/demo.cer" \
        -profileFile "signing/demo.p7b" \
        -inFile "./entry/build/default/outputs/default/entry-default.hap" \
        -keystoreFile "signing/idedemokey.p12" \
        -outFile "./entry/build/default/outputs/default/entry-default-signed.hap" \
        -keyPwd "${{ secrets.KEY_PASSWORD }}" \
        -keystorePwd "${{ secrets.KEYSTORE_PASSWORD }}" \
        -signCode "1"

    # 9. 上传 HAP 文件到 GitHub Release
    - name: Upload HAP to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # 获取上一步创建的 Release 的上传 URL
        asset_path: ./entry/build/default/outputs/default/entry-default-signed.hap
        asset_name: entry-default-signed.hap
        asset_content_type: application/octet-stream
